[package]
name = "aurac"
version = "0.0.2"
edition = "2021"
build = "build.rs"


[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }